- name: Déploiement du serveur sur plusieurs ports
  hosts: all
  become: true

  tasks:

    - name: Création d'un groupe utilisateur
      group:
        name: dream
        state: present

    - name: Création d'un utilisateur
      user:
        name: dblank
        comment: David Blank
        group: dream
        password: '*'

    - name: Installation du package nodejs
      package:
        name: nodejs
        state: present

    - name: Téléchargement du fichier server.js
      get_url:
        url: https://raw.githubusercontent.com/Sarabac/fourreTout/benjamin/server.js
        dest: ./server.js
    
    - name: Création d'un dossier pour les fichiers serveurs
      file:
        path: template
        state: directory
        group: dream
        owner: dblank
        mode: '755'

    - name: Création des fichiers serveurs à partir du template server.js
      template:
        src: ./server.js
        dest: template/server{{ NUM_FILE }}.js
        group: dream
        owner: dblank
        mode: '755'
    
    - name: Lancer les serveurs de manière asynchrone
      shell: node ./template/server{{ NUM_FILE }}.js &

    - name: Mise en pause du programme
      wait_for:
        port: "{{ SERVER_PORT }}"
        delay: 3
        sleep: 1
        timeout: 10

    - name: Vérifie la connection et retourne son status
      uri:
        url: http://localhost:{{ SERVER_PORT }}
        return_content: yes
      register: test
      failed_when: "'Hello' not in test.content"

    - name: Affiche le contenu de la page
      debug:
        msg: "{{ test.content | add_suffix | add_prefix | no_space }}"
    
    - name: Crée un fichier via un module perso
      my_module:
        path: './folder/'

    - name: Stopper les serveurs
      shell: pkill -f server{{ NUM_FILE }}.js