- name: Pratique de lookup
  gather_facts: no
  hosts: all
  # hosts: localhost
  # become: yes
  vars:
    my_env: "{{ lookup('env', 'HOME') }}"
    my_env2: "{{ lookup('pipe', 'ps') }}"
    my_file: "{{ lookup('file', './folder/file1.txt') }}"
    my_pwd: "{{ lookup('password', 'password.secret') }}"
    my_current_dir: "{{ lookup('pipe', 'pwd') }}"
  

  tasks:
    - name: Affiche le repertoire home de user
      debug:
        msg: "{{ my_env }}"
      
    - name: Affiche la sortie d'une commande (ps)
      debug:
        msg: "{{ my_env2 }}"

    - name: Lecture d'un fichier
      debug:
        msg: "{{ my_file }}"

    - name: Générer un mot de passe
      debug:
        msg: "{{ my_pwd }}"

    - name: Affiche le repertoire actuel
      debug:
        msg: "{{ my_current_dir }}"

    - name: Créer un fichier dans le répertoire user
      file:
        path: test_jenkins.txt
        state: touch
    