- name: Création et déploiement d'une base de donnée
  hosts: localhost
  become: true
  vars:
    SERVER_PORT: 3001

  tasks:

    - name: Installation des paquets
      package:
        name: "{{ item }}"
        state: present
        update_cache: true

      with_items:
        - python-pip
        - python-setuptools
        - mysql
        - docker
        - containerd
        - docker-compose
    
    - name: Installation des packets python
      pip:
        name:
          - mysql-connector-python
        state: present

    # - name: Initialisation du dossier de la base de donnée
    #   shell:
    #     cmd: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql

    # - name: Démarrage du service MySQL
    #   shell:
    #     cmd: systemctl start mysqld

    # - name: Vérification de la mise en route de MySQL
    #   service:
    #     name: mysql
    #     state: started
    #     enabled: true

    # - name: Création d'une base de donnée MySQL
    #   shell: 
    #     cmd: mysql < sql/init.sql

    # - name: insert exemple d'une ligne
    #   shell:
    #     cmd: mysql monitor < sql/insert.sql

    - name: Création d'un dossier pour les fichiers serveurs
      file:
        path: template
        state: directory

    - name: Téléchargement du fichier server.js
      get_url:
        url: https://raw.githubusercontent.com/Sarabac/fourreTout/benjamin/server.js
        dest: template/server.js

    - name: Création des fichiers serveurs à partir du template server.js
      template:
        src: template/server.js
        dest: template/server1.js
    
    # - name: Lancement du service docker
    #   shell:
    #     cmd: "systemctl start docker"

    # - name: Commande docker
    #   shell:
    #     cmd: "docker compose up -d"
    - name: Création du fichier de sauvegarde
      file:
        path: ./library/sauv.txt
        state: touch

    - name: exécuter server_gestion.py
      shell: python ./library/server_gestion.py