---

- name: Build du projet Java via Maven
  hosts: local
  roles:
    - maven_build

- name: Tâches du playbook server (rôle)
  hosts: server
  roles:
    - mariadb
    - server

- name: Tâches du playbook client (rôle)
  hosts: client
  roles:
    - client
