- name: Création et déploiement d'une base de donnée
  hosts: localhost
  become: true

  tasks:

    - name: Installation des paquets
      package:
        name: "{{ item }}"
        state: present

      with_items:
        - python-pip
        - python-setuptools
        - mysql

    - name: Initialisation du dossier de la base de donnée
      shell:
        cmd: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql

    - name: Démarrage du service MySQL
      shell:
        cmd: systemctl start mysqld

    - name: Vérification de la mise en route de MySQL
      service:
        name: mysql
        state: started
        enabled: true

    # - name: Mise à jour de l'utilisateur root et de son mot de passe
    #   community.mysql.mysql_user:  
    #     name: root
    #     password: admin
    #     host_all: true
    #     check_implicit_admin: true
    #     login_user: admin
    #     login_password: admin
    #     priv: '*.*:ALL'

    - name: Création d'une base de donnée MySQL
      community.mysql.mysql_db:
        name: bdd
        state: present

    - name: Création d'un utilisateur
      community.mysql.mysql_user:
        name: bob
        password: bob
        state: present

