- name: Création et déploiement d'une base de donnée
  hosts: localhost
  become: true

  tasks:

    - name: Installation des paquets
      package:
        name: "{{ item }}"
        state: present

      with_items:
        - python-pip
        - python-setuptools
        - mysql

    - name: Initialisation du dossier de la base de donnée
      shell:
        cmd: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql

    - name: Démarrage du service MySQL
      shell:
        cmd: systemctl start mysqld

    - name: Vérification de la mise en route de MySQL
      service:
        name: mysql
        state: started
        enabled: true

    # - name: Mise à jour de l'utilisateur root et de son mot de passe
    #   community.mysql.mysql_user:
    #     name: root
    #     password: root
    #     login_user: root
    #     login_password: root
    #     check_implicit_admin: true
    #     priv: '*.*:ALL'


    - name: Création d'une base de donnée MySQL
      shell: 
        cmd: mysql < sql/init.sql

    - name: insert exemple d'une ligne
      shell:
        cmd: mysql monitor < sql/insert.sql


    # Lancement des modules python en processus fils

