- name: essai-serveur
  hosts: all
  become: yes 
  tasks: 
    - name: thedossssssier
      file:
        path: endroit_serveur
        state : directory

    - name: thepouybelle
      file:
        path: "{{poubelle}}"
        state : directory

    - name: 
      get_url:
        url: https://raw.githubusercontent.com/Sarabac/fourreTout/benjamin/server.js
        dest: endroit_serveur/server.js.j2

    - name: template 
      template:  
        src: endroit_serveur/server.js.j2
        dest: "{{poubelle}}/server.js"

    - name: download paquet nodejs
      package: 
        name: nodejs
        state: present 

    - name: exe async nodejs
      shell: "nohup node {{poubelle}}/server.js &"
    
    - name: check that server ports are open, 10s before check
      wait_for:
        port: "{{SERVER_PORT}}"
        delay: 10

    - name: Check that the word hello is on the page
      uri:
        url: "http://localhost:{{SERVER_PORT}}"
        return_content: yes
      register: variable
      failed_when: "'Hello' not in variable.content"

    - name: print le contenu de variable.content
      debug:
        var: variable.content 

    - name: kill process
      shell: "pkill -f {{poubelle}}/server.js"
      ignore_errors: yes
