- name: essai-serveur
  hosts: all
  become: yes 
  tasks: 
    - name: thedossssssier
      file:
        path: endroit_serveur
        state : directory

    - name: thepouybelle
      file:
        path: poubelle
        state : directory

    - name: 
      get_url:
        url: https://raw.githubusercontent.com/Sarabac/fourreTout/benjamin/server.js
        dest: endroit_serveur/server.js.j2

    - name: template 
      template:  
        src: endroit_serveur/server.js.j2
        dest: poubelle/server.js

    - name: download paquet nodejs
      package: 
        name: nodejs
        state: present 

    - name: exe async nodejs
      shell: nohup node poubelle/server.js &

