---

- name: installer des paquets
  become: true 
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

  with_items:
    - jre11-openjdk

- name: créer un répertoire pr le projet morpion (partie client)
  ansible.builtin.file:
    path: "{{ dossier_client_morpion }}" 
    state: directory
    mode: '0755'

- name: exporter le fichier .sh sur le client
  ansible.builtin.copy :
    src: /home/bathou/Fourretout/morpion-bathilde/morpion_launcher.sh
    dest: "/home/local/{{ dossier_client_morpion }}/morpion_launcher.sh"
    owner: local
    mode: '755'

- name: exporter le jeu compilé en jar sur le client 
  ansible.builtin.copy :
    src: "/tmp/morpion/morpion-engine/target/{{ front_morpion_src }}"
    dest: "/home/local/{{ dossier_client_morpion }}/{{ front_morpion_dest }}"
    owner: local
    mode: '755'

- name: executer le fichier pour lancer le fichier .jar (sur la machine hote !)
  ansible.builtin.shell: ./morpion_launcher.sh
  args:
    chdir: "/home/local/{{ dossier_client_morpion }}"

      