---

- name: Installation de Java 11
  package:
    name: "{{ java_package_name }}"
    state: latest
  become: yes

- name: Création d'un dossier d'accueil pour les fichiers
  file:
    path: "{{ export_directory }}"
    state: directory
    mode: 0755

- name: Exportation du fichier .jar
  copy:
    src: "{{ java_backend_directory }}/{{ java_backend_file }}"
    dest: "{{ export_directory }}"
    mode: 0755

- name: Exportation du fichier (mariadb init)
  copy:
    src: files/init-morpion.sql
    dest: "{{ export_directory }}/init-morpion.sql"
    mode: 0755

- name: Initialisation de la BDD
  shell:
    cmd: "mariadb -u root < {{ export_directory }}/init-morpion.sql"
  become: yes

- name: Exportation du fichier application.yml
  template:
    src: template/application.yml
    dest: "{{ export_directory }}/application.yml"
    mode: 0755

- name: Lancement du fichier .jar
  shell:
    cmd: "nohup java -jar {{ export_directory }}/{{ java_backend_file }} --spring.config.location={{ export_directory }}/application.yml &"

- name: Ecoute du port 8080 (projet java)
  wait_for:
    port: "{{ server_port }}"
    delay: 3
    sleep: 1
    timeout: 15
  ignore_errors: true

- name: Vérification de la connection et affichage de son status
  uri:
    url: http://{{ ansible_host }}:{{ server_port }}/players
  ignore_errors: true
