---

- name: Installation de Java 11
  package:
    name: "{{ pkg_java }}"
    state: latest
  become: yes

- name: Création d'un dossier d'accueil pour les fichiers
  file:
    path: "{{ jar_dir }}"
    state: directory
    mode: 0755

- name: Exportation du fichier .jar
  copy:
    src: "{{ export_dir }}/{{ jar_file }}"
    dest: "{{ jar_dir }}"
    mode: 0755

- name: Lancement du fichier .jar
  shell:
    cmd: nohup java -jar {{ jar_dir }}/{{ jar_file }} &

- name: Vérification de la connection et affichage de son statusls

  uri:
    url: http://{{ ansible_host }}:{{ server_port }}/players
  ignore_errors: true
