---

- name: Installation de Java 11 sur la machine cible
  package:
    name: "{{ pkg_java }}"
    state: latest
  become: yes

- name: Création d'un dossier d'accueil pour le projet java
  file:
    path: "{{ jar_dir }}"
    state: directory
    mode: 0755

# - name: Exportation du fichier .sh sur la machine cible
#   copy:
#     src: "{{ export_dir }}/{{ sh_file }}"
#     dest: "{{ jar_dir }}"
#     mode: 0755

# - name: Execution du fichier .sh sur la machine cible
#   shell:
#     cmd: "{{ jar_dir }}/{{ sh_file }}"

- name: Exportation du fichier .jar sur la machine cible
  copy:
    src: "{{ export_dir }}/{{ jar_file }}"
    dest: "{{ jar_dir }}"

- name: Execution du fichier .jar sur la machine cible
  shell:
    cmd: nohup java -jar {{ jar_dir }}/{{ jar_file }}

# - name: Mise en pause du programme
#   wait_for:
#     port: 8080
#     delay: 3
#     sleep: 1
#     timeout: 10

# - name: Vérifie la connection et retourne son status
#   uri:
#     url: http://10.0.2.4:8080
#     return_content: yes
#   register: test
#   failed_when: "'Hello' not in test.content"
