---

- name: Installation de Java 11
  package:
    name: "{{ java_package_name }}"
    state: latest
  become: yes

- name: Création d'un dossier d'accueil pour les fichiers
  file:
    path: "{{ export_directory }}"
    state: directory
    mode: 0755

- name: Exportation du fichier .jar
  copy:
    src: "{{ java_backend_directory }}/{{ java_backend_file }}"
    dest: "{{ export_directory }}"
    mode: 0755

- name: Lancement du fichier .jar
  shell:
    cmd: java -jar {{ export_directory}}/{{ java_backend_file}} &
  ignore_errors: true

- name: Vérification de la connection et affichage de son status
  uri:
    url: http://{{ ansible_host }}:{{ server_port }}/players
  ignore_errors: true
