--insert into person VALUES (1, 'aze', 'jeanne', 'azerty');
--insert into person VALUES (2, 'sdfsdf', 'christian', '123456');
--insert into role VALUES (1, 'admin');
--insert into role VALUES (2, 'stagiaire');
--insert into assigned VALUES (1, 1, 1);
--insert into assigned VALUES  (2, 2, 2);
