---

- name: Installation de Java 11
  package:
    name: "{{ java_package_name }}"
    state: latest
  become: yes

- name: Création d'un dossier d'accueil pour les fichiers
  file:
    path: "{{ export_directory }}"
    state: directory
    mode: 0755

- name: Exportation du fichier .sh sur la machine cible
  copy:
    src: "{{ java_project_directory }}/{{ sh_test_file }}"
    dest: "{{ export_directory }}"
    mode: 0755

- name: Execution du fichier .sh sur la machine cible
  shell:
    cmd: "{{ export_directory }}/{{ sh_test_file }}"
